const help = require("./commands/help.js");
const requirements = require("./commands/requirements.js");
const role = require("./commands/role.js");
const game = require("./commands/game.js");
const admin = require("./commands/admin.js");
const modo = require("./commands/modo.js");
const event = require("./commands/event.js");
const morpion = require("./commands/morpion.js");
const power4 = require("./commands/power4.js");
const flip_coin = require("./commands/flip_coin.js");
const ranks = require("./commands/ranks.js");
const clean = require("./commands/clean.js");
const ping = require("./commands/ping.js");
const dice = require("./commands/dice.js");
const kick = require("./commands/kick.js");
const ban = require("./commands/ban.js");
const tag = require("./commands/tag.js");
const setChannel = require("./commands/setChannel.js");
const cmd = require("./commands/cmd.js");
const greetings = require("./commands/greetings.js");
const say = require("./commands/say.js");
const cv = require("./commands/cv.js");
const team = require("./commands/team.js");

var cmds = [];
cmds.push(say);
cmds.push(help);
cmds.push(requirements);
cmds.push(kick);
cmds.push(ban);
cmds.push(tag);
cmds.push(setChannel);
cmds.push(greetings);
cmds.push(cmd);
cmds.push(admin);
cmds.push(modo);
cmds.push(event);
cmds.push(cv);
cmds.push(team);
cmds.push(ranks);
cmds.push(role);
cmds.push(game);
cmds.push(morpion);
cmds.push(power4);
cmds.push(flip_coin);
cmds.push(dice);
cmds.push(clean);
cmds.push(ping);

module.exports = cmds;